version: '3.8'

services:
  # FastAPI Backend
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - DEVICE=cuda
      - USE_FP16=true
      - WHISPER_MODEL_SIZE=medium
      - USE_YOUTUBE_CAPTIONS=true
      - USE_WHISPER_AS_FALLBACK=true
      - USE_PDF_OCR=true
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./models:/app/models  # Map local models directory to container
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 8gb
    depends_on:
      - qdrant

  # Streamlit UI
  ui:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    restart: always
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    volumes:
      - ./models:/app/models  # Map local models directory to container
    env_file:
      - .env
    depends_on:
      - api

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CORS=true

volumes:
  qdrant-data: